const shopActionTypes = {
  SHOP_COLLECTION: "SHOP_COLLECTION",
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
  FETCH_COLLECTION_FAIL: "FETCH_COLLECTION_FAIL",
};

export default shopActionTypes;
